name: "Desktop Live ISO"
on:
  push:
    branches:
      - main
    paths:
      - desktop/*.nix
      - .github/workflows/desktop.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-23.11

      - run: nix-channel --add https://github.com/nix-community/home-manager/archive/release-23.11.tar.gz home-manager

      - run: nix-channel --update

      - run: nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=desktop/live.nix

      - uses: actions/upload-artifact@v4.0.0
        with:
          path: result/iso/*.iso
          compression-level: 0
