name: Netboot

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Quick Install Lix
        uses: canidae-solutions/lix-quick-install-action@v4

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Build
        run: nix-build -A netboot.kernel -A netboot.initrd -A netboot.ipxe -A shell

      - run: |
          touch tofu/terraform.tfvars
          chmod 0600 tofu/terraform.tfvars
          echo "${{ secrets.TERRAFORM_TFVARS }}" | base64 -d > tofu/terraform.tfvars

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v3

      - run: nix-shell -A opentofu --run "tofu init" ../shell.nix
        working-directory: ./tofu

      - run: |
          nix-shell -A opentofu --run "tofu apply -auto-approve -var pxe_bucket_ip_filter=false -target google_storage_bucket.pxe" ../shell.nix
          nix-shell -A opentofu --run "tofu apply -auto-approve -var pxe_bucket_ip_filter=false" ../shell.nix
          gcloud storage buckets remove-iam-policy-binding gs://${{ secrets.GCP_BUCKET }} --member=allUsers --role=roles/storage.objectViewer
        working-directory: ./tofu

      - run: |
          nix-shell -A opentofu --run "tofu apply -auto-approve -var pxe_bucket_ip_filter=true -exclude google_storage_bucket.pxe" ../shell.nix
          gcloud storage buckets add-iam-policy-binding gs://${{ secrets.GCP_BUCKET }} --member=allUsers --role=roles/storage.objectViewer
          nix-shell -A opentofu --run "tofu apply -auto-approve -var pxe_bucket_ip_filter=true -target google_storage_bucket.pxe" ../shell.nix
        working-directory: ./tofu
