name: "NixOS"
on:
  push:
    branches:
      - main
    paths:
      - rpi/configuration.nix
      - .github/workflows/nixos.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get -y install qemu-user-static

      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-23.11
          extra_nix_config: |
            extra-platforms = aarch64-linux

      - run: nix-build '<nixpkgs/nixos>' -I nixos-config=rpi/configuration.nix -A config.system.build.sdImage --argstr system aarch64-linux --option sandbox false

      - uses: actions/upload-artifact@v4.0.0
        with:
          path: result/sd-image/*.img
          compression-level: 0
