name: "NixOS"
on:
  push:
    branches:
      - main
    paths:
      - live.nix
      - .github/workflows/nixos.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-23.11

      - run: nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=live.nix

      - uses: actions/upload-artifact@v4.0.0
        with:
          path: result/iso/*.iso
          compression-level: 0
