name: "NixOS"
on:
  push:
    branches:
      - main
    paths:
      - live.nix
      - .github/workflows/nixos.yml
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - run: nix-build -A config.system.build.isoImage live.nix
#      - uses: actions/upload-artifact@v4.0.0
#        with:
#          path:
