name: Raspberry Pi SD image
on:
  push:
    branches:
      - main
    paths:
      - pi/*.nix
      - pi/flake.lock
      - .github/workflows/pi.yml
  workflow_dispatch:

jobs:
  build:
    name: Raspberry Pi SD image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v29

      - uses: cachix/cachix-action@v15
        with:
          name: drakon64-nixos-rpi
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix build .#images.pi.config.system.build.sdImage
        working-directory: pi

#      - run: |
#          ISO_FILE=(result/iso/*.iso)
#          echo ISO_FILE=$ISO_FILE >> $GITHUB_ENV
#          echo ISO_NAME=$(echo "$ISO_FILE" | sed -e 's/result\/iso\///' -e 's/.iso$//') >> $GITHUB_ENV
#        if: github.ref == 'refs/heads/main'

#      - uses: actions/upload-artifact@v4
#        with:
#          name: ${{ env.ISO_NAME }}
#          path: ${{ env.ISO_FILE }}
#          compression-level: 0
#          if-no-files-found: error
#        if: github.ref == 'refs/heads/main'
